version: "3.9"

services:
  patient-service1:
    image: postgres:16
    container_name: patient-service1
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"

  patient-service2:
    build: .
    container_name: patient-service2
    ports:
      - "3000:3000"
    depends_on:
      - patient-service1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service1:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
